Project_Semester/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SiswaController;
use App\Http\Controllers\AbsensiController;



Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/Dashboard', [App\Http\Controllers\AbsensiController::class, 'jumlah'])->name('Dashboard');
Route::get('/dashboard/{tanggal?}', [AbsensiController::class, 'jumlah'])->name('dashboard');
Route::get('/Generate', [App\Http\Controllers\AbsensiController::class, 'Generate'])->name('Generate');
Route::get('/export-all-excel', [AbsensiController::class, 'exportAllExcel'])->name('export.all.excel');
Route::get('/export-pdf', [AbsensiController::class, 'exportPdf'])->name('export.pdf');


Route::resource('siswa', SiswaController::class);

Route::resource('absensi', AbsensiController::class);

Project_Semester/app/Models/Absensi.php
<?php

// app/Models/Absensi.php
namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Absensi extends Model
{
    use HasFactory;
    protected $table = 'absensis';


    protected $fillable = ['nisn', 'nama_siswa', 'kehadiran', 'jam_masuk', 'jam_keluar', 'keterangan'];
}

Project_Semester/app/Http/Controllers/AbsensiController.php
<?php

// app/Http/Controllers/AbsensiController.php
namespace App\Http\Controllers;

use App\Exports\AbsensiExport;
use Maatwebsite\Excel\Facades\Excel;
use App\Models\Absensi;
use App\Models\siswa;
use Illuminate\Http\Request;
use Carbon\Carbon;
use Illuminate\Support\Facades\View;
use App\Http\Controllers\Controller;
use PDF;


class AbsensiController extends Controller
{
    public function index()
    {
        $absensis = Absensi::all();
        return view('absensi.index', compact('absensis'));
    }


    public function Generate()
    {
        // Pass default values or retrieve from your data
        return view('GenerateLaporan', ['kelas' => 'kelas7']);
    }

    public function exportAllExcel(Request $request)
    {
        // Tambahkan validasi untuk tanggal jika diperlukan
        $request->validate([
            'tanggal' => 'date', // Atau sesuaikan dengan aturan validasi yang diinginkan
        ]);

        $tanggal = $request->input('tanggal') ?? Carbon::now()->toDateString();
        $absensis = Absensi::whereDate('created_at', $tanggal)->get();

        return Excel::download(new AbsensiExport($absensis), 'absensi-' . $tanggal . '.xlsx');
    }

    public function exportPdf(Request $request)
    {
        // Tambahkan validasi untuk tanggal jika diperlukan
        $request->validate([
            'tanggal' => 'date', // Atau sesuaikan dengan aturan validasi yang diinginkan
        ]);

        $tanggal = $request->input('tanggal') ?? Carbon::now()->toDateString();
        $absensis = Absensi::whereDate('created_at', $tanggal)->get();

        $pdf = PDF::loadView('exportpdf', compact('absensis'));

        return $pdf->download('absensi-' . $tanggal . '.pdf');
    }


    public function jumlah($tanggal = null)
    {
        $tanggal = $tanggal ?? Carbon::now()->toDateString();

        $siswaCount = Siswa::count();

        $jumlahHadir = Absensi::where('kehadiran', 'Hadir')->whereDate('created_at', $tanggal)->count();
        $jumlahSakit = Absensi::where('kehadiran', 'Sakit')->whereDate('created_at', $tanggal)->count();
        $jumlahIzin = Absensi::where('kehadiran', 'Izin')->whereDate('created_at', $tanggal)->count();
        $jumlahAlfa = Absensi::where('kehadiran', 'Alfa')->whereDate('created_at', $tanggal)->count();

        // Mengonversi data ke tipe integer
        $jumlahHadir = (int)$jumlahHadir;
        $jumlahSakit = (int)$jumlahSakit;
        $jumlahIzin = (int)$jumlahIzin;
        $jumlahAlfa = (int)$jumlahAlfa;

        return view('Dashboard', compact('jumlahHadir', 'jumlahSakit', 'jumlahIzin', 'jumlahAlfa', 'siswaCount', 'tanggal'));
    }




    public function create()
    {
        return view('absensi.create');
    }

    public function store(Request $request)
    {
        // Validasi data input jika diperlukan
        $validatedData = $request->validate([
            'nisn' => 'required',
            'nama_siswa' => 'required',
            'kehadiran' => 'required',
            'jam_masuk' => 'required',
            'jam_keluar' => 'required',
            'keterangan' => 'required',


            // tambahkan validasi sesuai kebutuhan lainnya
        ]);

        Absensi::create($validatedData);

        return redirect()->route('absensi.index')->with('success', 'Data Absensi berhasil ditambahkan.');
    }

    public function show($id)
    {
        $absensi = Absensi::findOrFail($id);
        return view('absensi.show', compact('absensi'));
    }

    public function edit($id)
    {
        $absensi = Absensi::findOrFail($id);
        return view('absensi.edit', compact('absensi'));
    }

    public function update(Request $request, $id)
    {
        // Validasi data input jika diperlukan
        $validatedData = $request->validate([
            'nisn' => 'required',
            'nama_siswa' => 'required',
            'kehadiran' => 'required',
            'jam_masuk' => 'required',
            'jam_keluar' => 'required',
            'keterangan' => 'required',
        ]);

        $absensi = Absensi::findOrFail($id);
        $absensi->update($validatedData);

        return redirect()->route('absensi.index')->with('success', 'Data Absensi berhasil diperbarui.');
    }

    public function destroy($id)
    {
        $absensi = Absensi::findOrFail($id);
        $absensi->delete();

        return redirect()->route('absensi.index')->with('success', 'Data Absensi berhasil dihapus.');
    }
}

Project_Semester/resources/views/absensi/create.blade.php
<!-- resources/views/absensi/create.blade.php -->
@extends('layouts.app')

@section('content')
<div>
    <h2>Tambah Data Absensi</h2>
    <form action="{{ route('absensi.store') }}" method="POST">
        @csrf
        <div class="mb-3">
            <label for="nisn" class="form-label">NISN:</label>
            <input type="text" class="form-control" id="nisn" name="nisn" required>
        </div>
        <div class="mb-3">
            <label for="nama_siswa" class="form-label">Nama Siswa:</label>
            <input type="text" class="form-control" id="nama_siswa" name="nama_siswa" required>
        </div>
        <div class="mb-3">
            <label class="form-label">Kehadiran:</label>
            <div>
                <input type="radio" id="hadir" name="kehadiran" value="Hadir" required>
                <label for="hadir">Hadir</label>
            </div>
            <div>
                <input type="radio" id="sakit" name="kehadiran" value="Sakit" required>
                <label for="sakit">Sakit</label>
            </div>
            <div>
                <input type="radio" id="izin" name="kehadiran" value="Izin" required>
                <label for="izin">Izin</label>
            </div>
            <div>
                <input type="radio" id="alfa" name="kehadiran" value="Alfa" required>
                <label for="alfa">Alfa</label>
            </div>
        </div>

        <div class="mb-3">
            <label for="jam_masuk" class="form-label">Jam Masuk:</label>
            <input type="time" class="form-control" id="jam_masuk" name="jam_masuk" required>
        </div>
        <div class="mb-3">
            <label for="jam_keluar" class="form-label">Jam Keluar:</label>
            <input type="time" class="form-control" id="jam_keluar" name="jam_keluar" required>
        </div>
        <div class="mb-3">
            <label for="keterangan" class="form-label">keterangan:</label>
            <textarea class="form-control" id="keterangan" name="keterangan" rows="3"></textarea>
        </div>
        <!-- Tambahkan input fields sesuai kebutuhan -->
        <button type="submit" class="btn btn-primary">Simpan</button>
    </form>
</div>
@endsection

Project_Semester/resources/views/absensi/edit.blade.php
<!-- resources/views/absensi/edit.blade.php -->
@extends('layouts.app')

@section('content')
<div>
    <h2>Edit Data Absensi</h2>
    <form action="{{ route('absensi.update', $absensi->id) }}" method="POST">
        @csrf
        @method('PUT')
        <div class="mb-3">
            <label for="nisn" class="form-label">NISN:</label>
            <input type="text" class="form-control" id="nisn" name="nisn" value="{{ $absensi->nisn }}" required>
        </div>
        <div class="mb-3">
            <label for="nama_siswa" class="form-label">Nama Siswa:</label>
            <input type="text" class="form-control" id="nama_siswa" name="nama_siswa" value="{{ $absensi->nama_siswa }}" required>
        </div>
        <div class="mb-3">
            <label class="form-label">Kehadiran:</label>
            <div>
                <input type="radio" id="hadir" name="kehadiran" value="Hadir" required>
                <label for="hadir">Hadir</label>
            </div>
            <div>
                <input type="radio" id="sakit" name="kehadiran" value="Sakit" required>
                <label for="sakit">Sakit</label>
            </div>
            <div>
                <input type="radio" id="izin" name="kehadiran" value="Izin" required>
                <label for="izin">Izin</label>
            </div>
            <div>
                <input type="radio" id="alfa" name="kehadiran" value="Alfa" required>
                <label for="alfa">Alfa</label>
            </div>
        </div>
        <div class="mb-3">
            <label for="jam_masuk" class="form-label">Jam Masuk:</label>
            <input type="time" class="form-control" id="jam_masuk" name="jam_masuk" value="{{ $absensi->jam_masuk }}" required>
        </div>
        <div class="mb-3">
            <label for="jam_keluar" class="form-label">Jam Keluar:</label>
            <input type="time" class="form-control" id="jam_keluar" name="jam_keluar" value="{{ $absensi->jam_keluar }}" required>
        </div>
        <div class="mb-3">
            <label for="keterangan" class="form-label">Keterangan:</label>
            <textarea class="form-control" id="keterangan" name="keterangan" rows="3">{{ $absensi->keterangan }}</textarea>
        </div>
        <!-- Update input fields sesuai kebutuhan -->
        <button type="submit" class="btn btn-primary">Simpan Perubahan</button>
    </form>
</div>
@endsection

Project_Semester/resources/views/absensi/index.blade.php
<!-- resources/views/absensi/index.blade.php -->
@extends('layouts.app')

@section('content')


<div style="display: flex; align-items: center; justify-content: space-between; margin-bottom: 20px;">
    <div>
        <a href="{{ route('absensi.create') }}" class="btn btn-primary mb-3" style="background-color: #22DDD2;">
            <i class="fa fa-plus"></i> Tambah Data Absensi
        </a>
    </div>
</div>
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Daftar Absensi</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>NISN</th>
                        <th>Nama Siswa</th>
                        <th>Kehadiran</th>
                        <th>Jam Masuk</th>
                        <th>Jam Keluar</th>
                        <th>Tanggal Absensi</th>

                        <th>Keterangan</th>
                        <th>Aksi</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($absensis as $absensi)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $absensi->nisn }}</td>
                        <td>{{ $absensi->nama_siswa }}</td>
                        <td>{{ $absensi->kehadiran }}</td>
                        <td>{{ $absensi->jam_masuk }}</td>
                        <td>{{ $absensi->jam_keluar }}</td>
                        <td>{{ $absensi->created_at }}</td>
                        <td>{{ $absensi->keterangan }}</td>
                        <td>
                            <div style="display: flex; gap: 10px;">
                                <a href="{{ route('absensi.show', $absensi->id) }}" class="btn btn-info">Detail</a>
                                <a href="{{ route('absensi.edit', $absensi->id) }}" class="btn btn-primary">Edit</a>
                                <form action="{{ route('absensi.destroy', $absensi->id) }}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure a?')">Delete</button>
                                </form>
                            </div>
                        </td>

                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection

Project_Semester/resources/views/absensi/show.blade.php
<!-- resources/views/absensi/show.blade.php -->
@extends('layouts.app')

@section('content')
<div>
    <h2>Detail Absensi</h2>
    <p><strong>NISN:</strong> {{ $absensi->nisn }}</p>
    <p><strong>Nama Siswa:</strong> {{ $absensi->nama_siswa }}</p>
    <p><strong>Kehadiran:</strong> {{ $absensi->kehadiran }}</p>
    <p><strong>Jam Masuk:</strong> {{ $absensi->jam_masuk }}</p>
    <p><strong>Jam Keluar:</strong> {{ $absensi->jam_keluar }}</p>
    <p><strong>Keterangan:</strong> {{ $absensi->keterangan }}</p>
    <!-- Tampilkan detail lainnya sesuai kebutuhan -->

    <a href="{{ route('absensi.index') }}" class="btn btn-secondary">Kembali</a>
</div>
@endsection