Project_Semester/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SiswaController;
use App\Http\Controllers\AbsensiController;



Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/Dashboard', [App\Http\Controllers\AbsensiController::class, 'jumlah'])->name('Dashboard');
Route::get('/dashboard/{tanggal?}', [AbsensiController::class, 'jumlah'])->name('dashboard');
Route::get('/Generate', [App\Http\Controllers\AbsensiController::class, 'Generate'])->name('Generate');
Route::get('/export-all-excel', [AbsensiController::class, 'exportAllExcel'])->name('export.all.excel');
Route::get('/export-pdf', [AbsensiController::class, 'exportPdf'])->name('export.pdf');


Route::resource('siswa', SiswaController::class);

Route::resource('absensi', AbsensiController::class);

Project_Semester/app/Models/Siswa.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Siswa extends Model
{
    use HasFactory;

    protected $table = 'siswas';

    protected $fillable = ['nisn', 'nama', 'jenis_kelamin', 'kelas', 'no_hp'];
}

Project_Semester/app/Http/Controllers/SiswaController.php
<?php

// app/Http/Controllers/SiswaController.php

namespace App\Http\Controllers;

use App\Models\Siswa;
use Illuminate\Http\Request;

class SiswaController extends Controller
{
    public function index()
    {
        $siswas = Siswa::all();
        return view('siswa.index', compact('siswas'));
    }

   

    public function create()
    {
        return view('siswa.create');
    }

    public function store(Request $request)
    {
        Siswa::create($request->all());
        return redirect()->route('siswa.index')->with('success', 'Siswa created successfully');
    }

    public function show(Siswa $siswa)
    {
        return view('siswa.show', compact('siswa'));
    }

    public function edit(Siswa $siswa)
    {
        return view('siswa.edit', compact('siswa'));
    }

    public function update(Request $request, Siswa $siswa)
    {
        $siswa->update($request->all());
        return redirect()->route('siswa.index')->with('success', 'Siswa updated successfully');
    }

    public function destroy(Siswa $siswa)
    {
        $siswa->delete();
        return redirect()->route('siswa.index')->with('success', 'Siswa deleted successfully');
    }
}

Project_Semester/resources/views/Siswa/create.blade.php
<!-- resources/views/siswa/create.blade.php -->

@extends('layouts.app')

@section('content')
<div>
    <a href="{{ route('siswa.index') }}" class="btn btn-secondary mb-3">
        <i class="fa fa-arrow-left"></i> Kembali
    </a>
</div>

@if($errors->any())
<div class="alert alert-danger">
    <ul>
        @foreach($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Tambah Data Siswa</h6>
    </div>
    <div class="card-body">
        <form action="{{ route('siswa.store') }}" method="POST">
            @csrf
            <div class="mb-3">
                <label for="nisn" class="form-label">NISN:</label>
                <input type="text" class="form-control" id="nisn" name="nisn" required>
            </div>
            <div class="mb-3">
                <label for="nama" class="form-label">Nama Siswa:</label>
                <input type="text" class="form-control" id="nama" name="nama" required>
            </div>
            <div class="mb-3">
                <label class="form-label">Jenis Kelamin:</label>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="jenis_kelamin" id="laki-laki" value="Laki-laki" checked>
                    <label class="form-check-label" for="laki-laki">Laki-laki</label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="jenis_kelamin" id="perempuan" value="Perempuan">
                    <label class="form-check-label" for="perempuan">Perempuan</label>
                </div>
            </div>

            <div class="mb-3">
                <label for="kelas" class="form-label">Kelas:</label>
                <select class="form-select" id="kelas" name="kelas" required style="width: 100%; font-size: 16px; padding: 7px;">
                    <option value="" disabled selected>Select Kelas</option>
                    <option value="7">Kelas 7</option>
                    <option value="8">Kelas 8</option>
                    <option value="9">Kelas 9</option>
                </select>
            </div>


            <div class="mb-3">
                <label for="no_hp" class="form-label">No Hp:</label>
                <input type="text" class="form-control" id="no_hp" name="no_hp" required>
            </div>
            <button type="submit" class="btn btn-primary">Simpan</button>
        </form>
    </div>
</div>
@endsection

Project_Semester/resources/views/Siswa/edit.blade.php
<!-- resources/views/siswa/edit.blade.php -->

@extends('layouts.app')

@section('content')
<div>
    <a href="{{ route('siswa.index') }}" class="btn btn-secondary mb-3">
        <i class="fa fa-arrow-left"></i> Kembali
    </a>
</div>

@if($errors->any())
<div class="alert alert-danger">
    <ul>
        @foreach($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Edit Data Siswa</h6>
    </div>
    <div class="card-body">
        <form action="{{ route('siswa.update', $siswa->id) }}" method="POST">
            @csrf
            @method('PUT')
            <div class="mb-3">
                <label for="nisn" class="form-label">NISN:</label>
                <input type="text" class="form-control" id="nisn" name="nisn" value="{{ $siswa->nisn }}" required>
            </div>
            <div class="mb-3">
                <label for="nama" class="form-label">Nama Siswa:</label>
                <input type="text" class="form-control" id="nama" name="nama" value="{{ $siswa->nama }}" required>
            </div>
            <div class="mb-3">
                <label class="form-label">Jenis Kelamin:</label>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="jenis_kelamin" id="laki-laki" value="Laki-laki" checked>
                    <label class="form-check-label" for="laki-laki">Laki-laki</label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="jenis_kelamin" id="perempuan" value="Perempuan">
                    <label class="form-check-label" for="perempuan">Perempuan</label>
                </div>
            </div>

            <div class="mb-3">
                <label for="kelas" class="form-label">Kelas:</label>
                <select class="form-select" id="kelas" name="kelas" required style="width: 100%; font-size: 16px; padding: 7px;">
                    <option value="" disabled selected>Select Kelas</option>
                    <option value="7">Kelas 7</option>
                    <option value="8">Kelas 8</option>
                    <option value="9">Kelas 9</option>
                </select>
            </div>
            <div class="mb-3">
                <label for="no_hp" class="form-label">No Hp:</label>
                <input type="text" class="form-control" id="no_hp" name="no_hp" value="{{ $siswa->no_hp }}" required>
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
</div>
@endsection

Project_Semester/resources/views/Siswa/index.blade.php
<!-- resources/views/siswa/index.blade.php -->

@extends('layouts.app')

@section('content')


<div style="display: flex; align-items: center; justify-content: space-between; margin-bottom: 20px;">

<div>
    <a href="{{ route('siswa.create') }}" class="btn btn-primary mb-3" style="background-color: #22DDD2;">
        <i class="fa fa-plus"></i> Tambah Data Siswa
    </a>
</div>

<div class="mb-3" style="margin-left: 10px;">
    <label for="classFilter" class="form-label" style="font-size: 16px;">Filter Kelas:</label>
    <select class="form-select" id="classFilter" style="font-size: 16px; padding: 5px;" onchange="filterTable()">
        <option value="semua" selected>Semua</option>
        <option value="7">Kelas 7</option>
        <option value="8">Kelas 8</option>
        <option value="9">Kelas 9</option>
    </select>
</div>
</div>

@if(session('success'))
<div class="alert alert-success">
    {{ session('success') }}
</div>
@endif

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Daftar Siswa</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>NISN</th>
                        <th>Nama Siswa</th>
                        <th>Jenis Kelamin</th>
                        <th>Kelas</th>
                        <th>No Hp</th>
                        <th>Aksi</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($siswas as $siswa)
                    <tr data-class="kelas{{ $siswa->kelas }}">
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $siswa->nisn }}</td>
                        <td>{{ $siswa->nama }}</td>
                        <td>{{ $siswa->jenis_kelamin }}</td>
                        <td>{{ $siswa->kelas }}</td>
                        <td>{{ $siswa->no_hp }}</td>
                        <td>
                            <div style="display: flex; gap: 10px;">
                                <a href="{{ route('siswa.show', $siswa->id) }}" class="btn btn-info">Detail</a>
                                <a href="{{ route('siswa.edit', $siswa->id) }}" class="btn btn-primary">Edit</a>
                                <form action="{{ route('siswa.destroy', $siswa->id) }}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure?')">Delete</button>
                                </form>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
    function filterTable() {
        // Dapatkan nilai filter yang dipilih
        var selectedFilter = document.getElementById('classFilter').value;

        // Dapatkan semua baris tabel
        var rows = document.getElementById('dataTable').getElementsByTagName('tr');

        // Iterasi melalui setiap baris dan tampilkan/sembunyikan berdasarkan filter
        for (var i = 1; i < rows.length; i++) { // Dimulai dari 1 untuk melewati baris judul
            var row = rows[i];
            var classValue = row.getAttribute('data-class');

            // Tampilkan baris jika "Semua" dipilih atau jika kelas cocok dengan filter
            if (selectedFilter === 'semua' || classValue === 'kelas' + selectedFilter) {
                row.style.display = '';
            } else {
                row.style.display = 'none';
            }
        }
    }
</script>
@endsection

Project_Semester/resources/views/Siswa/show.blade.php
<!-- resources/views/siswa/show.blade.php -->

@extends('layouts.app')

@section('content')
<div>
    <a href="{{ route('siswa.index') }}" class="btn btn-secondary mb-3">
        <i class="fa fa-arrow-left"></i> Kembali
    </a>
</div>

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Detail Siswa</h6>
    </div>
    <div class="card-body">
        <table class="table">
            <tr>
                <td><strong>NISN:</strong></td>
                <td>{{ $siswa->nisn }}</td>
            </tr>
            <tr>
                <td><strong>Nama Siswa:</strong></td>
                <td>{{ $siswa->nama }}</td>
            </tr>
            <tr>
                <td><strong>Jenis Kelamin:</strong></td>
                <td>{{ $siswa->jenis_kelamin }}</td>
            </tr>
            <tr>
                <td><strong>Kelas:</strong></td>
                <td>{{ $siswa->kelas }}</td>
            </tr>
            <tr>
                <td><strong>No Hp:</strong></td>
                <td>{{ $siswa->no_hp }}</td>
            </tr>
        </table>
    </div>
</div>
@endsection